# Generated by Django 3.2.8 on 2021-10-10 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('website', '0001_initial'),
        ('watchlist', '0001_initial'),
        ('crypto', '0001_initial'),
        ('markets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist_userprofile', to='website.userprofile'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='coins',
            field=models.ManyToManyField(blank=True, related_name='portfolio_cryptocurrency', through='watchlist.Amounts', to='crypto.Cryptocurrency'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_currency', to='markets.currency'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_userprofile', to='website.userprofile'),
        ),
        migrations.AddField(
            model_name='amounts',
            name='coin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amounts_coin', to='crypto.cryptocurrency'),
        ),
        migrations.AddField(
            model_name='amounts',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amounts_portfolio', to='watchlist.portfolio'),
        ),
    ]
