# Generated by Django 3.2.8 on 2021-10-10 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, null=True)),
                ('symbol', models.CharField(max_length=3, unique=True)),
                ('country', models.CharField(blank=True, max_length=32, null=True)),
            ],
        ),
    ]
