# Generated by Django 3.2.8 on 2021-10-10 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
