# Generated by Django 3.2.8 on 2021-10-10 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('markets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cryptocurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('symbol', models.CharField(max_length=8)),
                ('description', models.TextField(max_length=256)),
                ('url', models.CharField(blank=True, max_length=32, null=True)),
                ('algorithm', models.CharField(max_length=32)),
                ('proof_type', models.CharField(max_length=32)),
                ('total_coins_mined', models.FloatField(blank=True, null=True)),
                ('circulating_supply', models.FloatField(blank=True, null=True)),
                ('max_supply', models.FloatField(blank=True, null=True)),
                ('used_in_defi', models.BooleanField(blank=True, null=True)),
                ('used_in_nft', models.BooleanField(blank=True, null=True)),
                ('block_reward', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('country', models.CharField(max_length=32)),
                ('grade', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('NA', 'NA')], default='NA', max_length=3)),
                ('url', models.CharField(default='', max_length=32)),
                ('volume', models.FloatField(default=0)),
                ('coins', models.ManyToManyField(blank=True, related_name='exchange_coins', to='crypto.Cryptocurrency')),
            ],
        ),
        migrations.CreateModel(
            name='Ticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_price', models.FloatField(default=0)),
                ('ask_price', models.FloatField(default=0)),
                ('hourly_change', models.FloatField(default=0)),
                ('daily_change', models.FloatField(default=0)),
                ('weekly_change', models.FloatField(default=0)),
                ('monthly_change', models.FloatField(default=0)),
                ('base_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crypto.cryptocurrency')),
                ('quote_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='markets.currency')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crypto.exchange')),
            ],
        ),
        migrations.CreateModel(
            name='ExchangeCoins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchangecoins_coin', to='crypto.cryptocurrency')),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchangecoins_exchange', to='crypto.exchange')),
            ],
        ),
    ]
